Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "nginx-cache" do |vm1|
    vm1.vm.network "private_network", ip: "192.168.1.101"
  end  

  config.vm.define "apache-cache" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.1.102"
  end  

  config.vm.define "nginx-reverse" do |vm3|
    vm3.vm.network "private_network", ip: "192.168.1.103"
  end  

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

end